version: '3'

services:
    zookeeper:
        image: sirmaxwill/zookeeper
        container_name: zookeeper
        ports:
            - "2181:2182"
    kafka:
        image: sirmaxwill/kafka
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        